"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


@pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` to [dev]",
)
def test_audit_all_for_scitex_introspect_is_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    audit_all_for_package("scitex-introspect")
    # Assert
    # audit_all_for_package raises on violation; reaching this line means clean.
    assert True
